/* The papers, as the first engine had them. Two of them carry codes that change every run (the Armory keypad, and
   Holt's office keypad on floor 4); the sim draws them from the run's seed. */

export interface Note { t: string; b: string }

export const NOTES = (code: string, code2: string): Record<string, Note> => ({
  intake:{t:'Isolation record, room 1',b:`LOWFIELD STATION / SECURITY, MEDICAL ISOLATION\n\nRoom 1. Staff, own quarters sealed.\nIsolated by order of the Director of Operations. Reason: not stated.\nBloods taken. Results: pending.\n\nDoors on the fail-safe. Observe from the station. Do not go in alone.\n\nSigned: Sgt. R. Aldana`},
  duty:{t:'Station log, isolation',b:`We cut the wing's feed ourselves this morning. The cameras on this side are blind now, and so are we. Every door in the suite let go when the lights did. That is the law and I am not arguing with it today: nobody in there is any trouble.\n\nThe rest of the floor is on its backup set. Half-light in their halls, and their doors open for anything that walks up to them. Ours slide by hand now. So do theirs, for them: the staff who took badly still walk like people and still do rounds, and they can slide a dead door open as well as you can. They cannot get under a jammed one or work a heavy door.\n\nThey keep to the light. Stay in the dark and keep still.\n\nTorch is with me. Baton is on the bench.`},
  cams:{t:'Shift note, security control',b:`Camera coverage follows the power. Right now that is this floor and nothing else.\n\nReminder that Horticulture is not on our board and never was. They have their own post, their own passes and their own backup set. We send people down. We do not get to watch what happens to them.\n\nThe surface lift takes an Armory pass or the director's key. The director took his key home to floor 3 and has not been seen at a briefing since.`},
  lockers:{t:'Taped inside a locker door',b:`The ops room bolts itself now. Nobody is in there to do it. Nobody we would call anybody.\n\nReyes says that door is not on the main board. It has its own feed from the electrical room at the west end of the hall, and a bolt with no power behind it is just a lock you can slide. Reyes went to find out.\n\nThe hall lights are still on. The big one is still in the hall.`},
  memo:{t:'Staff memo: the Regimen',b:`To all Lowfield staff,\n\nThe tissue Horticulture recovered from the aquifer core accepts any graft we give it and asks nothing in return. It began in the seed beds. It did not stay in the seed beds. Dr. Holt burned her hand in March. Many of you have seen her hand.\n\nFrom Monday the Regimen is open to every member of staff, on a voluntary basis. One small graft. You will sleep less and need less. You will find the dark down here easier to bear.\n\nWe came to grow things where nothing grows. I see no reason to stop at wheat.\n\nOperations, on behalf of Dr. Maren Holt`},
  mgr:{t:'Note to the chief of security',b:`The Armory keypad was changed last week and I was not given the number. I am told Sgt. Aldana has it, on her person, and that Sgt. Aldana went down to Hydro on 6 to look at the flooding and has not come back up.\n\nI would like it noted that the only surface passes on this station are inside that Armory.\n\nI would also like it noted that the Armory is a heavy door, so the number is no use to anyone until Gen-1 is running.`},
  chief:{t:'Chief of security, unsent',b:`Things I have signed for: thirty-one transfers from Holding to floor 4. Nothing has ever come back up.\n\nHazard store has the rebreathers. If anyone has to go after Aldana, that is what they will need, and that door is a heavy one too.\n\nThe ones on 3 have stopped being staff. They keep the Commons like a territory. They have started carrying their clutches up to Cargo and laying them on the high rungs, where nothing green can reach.`},
  manifest:{t:'Cargo manifest, bay 2',b:`UPPER RUNG, BAY 2: one crate electrical spares for Engineering, incl. GEN-1 MAIN FUSE x1. Not yet sent down.\n\nThe platforms need power to move. The backup set in this office will do it. It will also wake every door on the floor, and I would think hard about that, because of what is on the rungs.\n\nThey do not like light. The small ones cannot open anything. The ones that walk can.\n\nStairs down are at the far end of bay 2.`},
  diary:{t:'A resident\'s diary',b:`Eleven days without sleep and I have never felt better. Everyone at breakfast says the same. Nobody is eating much breakfast.\n\nPia keeps her arm under the blanket now. I watched it reach for the lamp while she was looking the other way, and then it turned the lamp off.\n\nThey pulled up everything green in the Commons last night. All of it, with their hands. The tree is the only thing they could not shift, and it has started to look like them.\n\nThe unmarked door past the trauma centre is the stair to Horticulture. We were never meant to notice it.`},
  clinic:{t:'Clinical notes, trauma centre',b:`A cultivar that takes badly is not a failure of the rootstock. It is a failure of the scion.\n\nFour staff have taken badly. I have moved them where it is dark and they are calmer.\n\nThis ward is to be left exactly as it is. Nobody here is going to need it.\n\nOffice keypad, floor 4, since I no longer trust myself to remember what I no longer care about: ${code2}.\n\nM. H.`},
  keeper:{t:'On the director\'s desk',b:`I was going to take the surface lift. I had the key round my neck and my hand on the door.\n\nThen I thought: up there I am a man who signed for thirty-one people. Down here they bring me things.\n\nI have decided to stay. I find I am becoming easier to stay with.`},
  hsec:{t:'Horticulture security log',b:`Nobody from upstairs comes through this post without one of our passes. That is the point of the post.\n\nThe beds stopped needing light in the spring. Then they stopped needing beds. It is in the grout. It is in the cable trays. It has gone down the west stair into Engineering and nobody down there has called up in a week.\n\nIt does not go up. Whatever the staff on 3 have become, they tear it out wherever it shows.\n\nThe hanging growth over the doorways is not growth. Hit the pod, not the tendrils.`},
  journal:{t:'Holt\'s lab journal',b:`I was afraid for most of a year. Of the board, of the tissue, of what Operations kept signing for on my behalf.\n\nFear lives in a place. I know where, now. I went in through the orbit with a number eleven blade and a mirror, and I took it out. It was smaller than I expected.\n\nI can no longer find any reason to have stopped at one graft, so I haven't.\n\nIt takes plants first. Then whatever lives on plants. Then whatever tends them.`},
  holt:{t:'Director of research, memorandum',b:`Accessions are to be routed from Holding directly to the tissue lab. They are not to pass through the Commons. They are not to be given names in my hearing.\n\nIf Engineering complain again about roots in the switchgear, remind them who keeps the lights on for whom.`},
  last:{t:'A page left in the soil',b:`I am going to sit in the arboretum. The light is good there, and I find I want very little else.\n\nThe ones upstairs think they are at war with the garden. They are the garden. They are the part of it that walks.\n\nIf you are one of mine: you were never a prisoner. You were stock. It is a better thing to be.\n\nM.`},
  work:{t:'Work order 2217',b:`GEN-1 MAIN FUSE: BLOWN (third time)\n\nOne spare on the bench in the machine shop. One more in a crate that never came down from Cargo.\n\nSeat the fuse in the socket on the generator hall board, THEN throw the breaker. The breaker goes both ways.\n\nGen-1 feeds every floor through the board in Distribution. A closed switch takes power. An open one does not. Cargo was opened on purpose and should probably stay that way. Hydro's feed burned through when the bottom level flooded: it wants a splice kit, and even then you will only light the top half. Nothing lights what is under water.\n\nKits are in the parts store. The parts store is on my card.\n\nThe green stuff from the west stair is in the shop now. Do not walk under the hanging ones.`},
  route:{t:'Chalked on the floor, Distribution',b:`1 OPS .... closed\n2 CARGO .. OPEN (leave it)\n3 RES .... closed\n4 HORT ... closed\n6 HYDRO .. BURNED\n\nEach floor also has its own backup set. Half-light, sliding doors, card readers. No heavy doors. No lifts.`},
  hydro:{t:'Pump control, last entry',b:`Lower level is gone. Both shafts are full to the hatch.\n\nAldana went down shaft A after the pump crew with a torch. Torches die under water. I told her. The dive lantern is on this desk because she would not take it.\n\nIf you have to go after her: shaft B in the filter room comes out much nearer the sluice than A does. On one breath, B is possible and A is not. With a rebreather either will do. The rebreathers are in the hazard store on 1, naturally.\n\nYou will not see your hand without goggles. Somebody in Recreation on 3 used to swim.\n\nLight brings the swimmers.`},
  code:{t:'Written on Aldana\'s hand',b:`ARMORY\n\n${code}`}
});
